# Copyright 2020 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
defaultLocale: en
category: GAMES_AND_TRIVIA
localizedSettings:
  developerEmail: example@example.com
  developerName: Example Developer Name
  fullDescription: Facts About Google Action.
  pronunciation: Facts About Google test
  privacyPolicyUrl: https://example.com
  sampleInvocations:
  - talk to Facts About Google test
  shortDescription: Facts About Google test action.
projectId: <PROJECT_ID>
usesInteractiveCanvas: true
